%%{init: {"flowchart": {"htmlLabels": false}} }%%
flowchart LR
    subgraph fav_sports
        direction LR
        id1[Bob]
        value1[football]
        id1 --> value1
        id2[Rahul]
        value2[hockey]
        id2 --> value2
        id3[Paul]
        value3[battle bots]
        id3 --> value3
        id4[Parker]
        value4[tennis]
        id4 --> value4
    end

